/*
 * generated by Xtext 2.28.0-SNAPSHOT
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.MCC.ui.internal.MCCActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MCCExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MCCActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MCCActivator activator = MCCActivator.getInstance();
		return activator != null ? activator.getInjector(MCCActivator.ORG_XTEXT_MCC) : null;
	}

}
