/*
 * generated by Xtext 2.28.0-SNAPSHOT
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.MCC.ui.internal.MCCActivator;

public class MCCUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MCCActivator.getInstance().getInjector("org.xtext.MCC");
	}

}
