/*
 * generated by Xtext 2.28.0-SNAPSHOT
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MCCUiModule extends AbstractMCCUiModule {

	public MCCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
