/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fragment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mCC.Fragment#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mCC.Fragment#getInstructions <em>Instructions</em>}</li>
 *   <li>{@link org.xtext.mCC.Fragment#getMemory <em>Memory</em>}</li>
 *   <li>{@link org.xtext.mCC.Fragment#getSync <em>Sync</em>}</li>
 *   <li>{@link org.xtext.mCC.Fragment#getIsOfflodable <em>Is Offlodable</em>}</li>
 *   <li>{@link org.xtext.mCC.Fragment#getInit <em>Init</em>}</li>
 * </ul>
 *
 * @see org.xtext.mCC.MCCPackage#getFragment()
 * @model
 * @generated
 */
public interface Fragment extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mCC.MCCPackage#getFragment_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Fragment#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Instructions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instructions</em>' attribute.
   * @see #setInstructions(int)
   * @see org.xtext.mCC.MCCPackage#getFragment_Instructions()
   * @model
   * @generated
   */
  int getInstructions();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Fragment#getInstructions <em>Instructions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Instructions</em>' attribute.
   * @see #getInstructions()
   * @generated
   */
  void setInstructions(int value);

  /**
   * Returns the value of the '<em><b>Memory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Memory</em>' attribute.
   * @see #setMemory(int)
   * @see org.xtext.mCC.MCCPackage#getFragment_Memory()
   * @model
   * @generated
   */
  int getMemory();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Fragment#getMemory <em>Memory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Memory</em>' attribute.
   * @see #getMemory()
   * @generated
   */
  void setMemory(int value);

  /**
   * Returns the value of the '<em><b>Sync</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sync</em>' attribute.
   * @see #setSync(int)
   * @see org.xtext.mCC.MCCPackage#getFragment_Sync()
   * @model
   * @generated
   */
  int getSync();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Fragment#getSync <em>Sync</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sync</em>' attribute.
   * @see #getSync()
   * @generated
   */
  void setSync(int value);

  /**
   * Returns the value of the '<em><b>Is Offlodable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Offlodable</em>' attribute.
   * @see #setIsOfflodable(String)
   * @see org.xtext.mCC.MCCPackage#getFragment_IsOfflodable()
   * @model
   * @generated
   */
  String getIsOfflodable();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Fragment#getIsOfflodable <em>Is Offlodable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Offlodable</em>' attribute.
   * @see #getIsOfflodable()
   * @generated
   */
  void setIsOfflodable(String value);

  /**
   * Returns the value of the '<em><b>Init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' attribute.
   * @see #setInit(String)
   * @see org.xtext.mCC.MCCPackage#getFragment_Init()
   * @model
   * @generated
   */
  String getInit();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Fragment#getInit <em>Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init</em>' attribute.
   * @see #getInit()
   * @generated
   */
  void setInit(String value);

} // Fragment
