/**
 * generated by Xtext 2.34.0
 */
package org.xtext.mCC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mobile</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mCC.Mobile#getBattery <em>Battery</em>}</li>
 *   <li>{@link org.xtext.mCC.Mobile#getNetwork <em>Network</em>}</li>
 *   <li>{@link org.xtext.mCC.Mobile#getMemory <em>Memory</em>}</li>
 * </ul>
 *
 * @see org.xtext.mCC.MCCPackage#getMobile()
 * @model
 * @generated
 */
public interface Mobile extends Device
{
  /**
   * Returns the value of the '<em><b>Battery</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Battery</em>' attribute.
   * @see #setBattery(int)
   * @see org.xtext.mCC.MCCPackage#getMobile_Battery()
   * @model
   * @generated
   */
  int getBattery();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Mobile#getBattery <em>Battery</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Battery</em>' attribute.
   * @see #getBattery()
   * @generated
   */
  void setBattery(int value);

  /**
   * Returns the value of the '<em><b>Network</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Network</em>' attribute.
   * @see #setNetwork(int)
   * @see org.xtext.mCC.MCCPackage#getMobile_Network()
   * @model
   * @generated
   */
  int getNetwork();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Mobile#getNetwork <em>Network</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Network</em>' attribute.
   * @see #getNetwork()
   * @generated
   */
  void setNetwork(int value);

  /**
   * Returns the value of the '<em><b>Memory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Memory</em>' attribute.
   * @see #setMemory(int)
   * @see org.xtext.mCC.MCCPackage#getMobile_Memory()
   * @model
   * @generated
   */
  int getMemory();

  /**
   * Sets the value of the '{@link org.xtext.mCC.Mobile#getMemory <em>Memory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Memory</em>' attribute.
   * @see #getMemory()
   * @generated
   */
  void setMemory(int value);

} // Mobile
